name: 'Lemonade Docker Image CI'
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["linux-appimage", "linux-fresh"]
    
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
      name: Setup Docker BuildX system
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}
    - uses: docker/build-push-action@v4
      name: Build image
      with:
        push: true
        context: ${{ matrix.image }}
        tags: ishan09811/build-environments:${{ matrix.image }}
